(in-package "CLOGPOWER")
(defclass clog-lichat-talker (clog:clog-panel)
  (    (chat-send :reader chat-send)
    (chat-box :reader chat-box)
    (chat-area :reader chat-area)
(chat :accessor chat)))
(defun create-clog-lichat-talker (clog-obj &key (hidden nil) (class nil) (html-id nil) (auto-place t))
  (let ((panel (change-class (clog:create-div clog-obj :content "<textarea name=\"\" cols=\"20\" rows=\"2\" wrap=\"\" style=\"box-sizing: content-box; position: absolute; left: 0px; bottom: 0px; width: 75%; height: 20%; resize: none;\" id=\"CLOGB3858099510\"></textarea><div style=\"box-sizing: content-box; position: absolute; left: 0px; top: 0px; width: 98%; height: 78%; overflow: auto; resize: none;\" id=\"CLOGB3858099511\" class=\"w3-monospace\"></div><button style=\"box-sizing: content-box; position: absolute; height: 20%; width: 20%; bottom: 0px; right: 0px;\" id=\"CLOGB3858099512\">Send</button>"
         :hidden hidden :class class :html-id html-id :auto-place auto-place) 'clog-lichat-talker)))
    (setf (slot-value panel 'chat-send) (attach-as-child clog-obj "CLOGB3858099512" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'chat-box) (attach-as-child clog-obj "CLOGB3858099511" :clog-type 'CLOG:CLOG-DIV :new-id t))
    (setf (slot-value panel 'chat-area) (attach-as-child clog-obj "CLOGB3858099510" :clog-type 'CLOG:CLOG-TEXT-AREA :new-id t))
    (set-on-click (chat-send panel) (lambda (target) (declare (ignorable target)) (send-message panel)))
    panel))
